# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactWBL', '0003_auto_20190825_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'first year'), ('2', 'second year'), ('3', 'third year'), ('4', 'fourth year'), ('5', 'postgraduate')], max_length=8, null=True),
        ),
    ]
